accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000arazor"]
  - name: bob
    coins: ["5000000000000arazor"]
validator:
  name: alice
  staked: "100000000000000000000arazor"
faucet:
  name: bob
  coins: ["10arazor"]
build:
  binary: "razord"
init:
  home: "$HOME/.razord"
  app:
    evm-rpc:
      address: "0.0.0.0:8545" # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546" # change the JSON-RPC websocket address and port
genesis:
  chain_id: "razord_777-1"
  app_state:
    staking:
      params:
        bond_denom: "arazor"
    mint:
      params:
        mint_denom: "arazor"
    crisis:
      constant_fee:
        denom: "arazor"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "arazor"
    evm:
      params:
        evm_denom: "arazor"
