// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: canto/csr/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// This is a wrapper around the CSR proto that returns the CSR and revenue in the form of a string.
type WrappedCSR struct {
	Csr           CSR    `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr"`
	RevenueString string `protobuf:"bytes,2,opt,name=revenue_string,json=revenueString,proto3" json:"revenue_string,omitempty"`
}

func (m *WrappedCSR) Reset()         { *m = WrappedCSR{} }
func (m *WrappedCSR) String() string { return proto.CompactTextString(m) }
func (*WrappedCSR) ProtoMessage()    {}
func (*WrappedCSR) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{0}
}
func (m *WrappedCSR) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WrappedCSR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WrappedCSR.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WrappedCSR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrappedCSR.Merge(m, src)
}
func (m *WrappedCSR) XXX_Size() int {
	return m.Size()
}
func (m *WrappedCSR) XXX_DiscardUnknown() {
	xxx_messageInfo_WrappedCSR.DiscardUnknown(m)
}

var xxx_messageInfo_WrappedCSR proto.InternalMessageInfo

func (m *WrappedCSR) GetCsr() CSR {
	if m != nil {
		return m.Csr
	}
	return CSR{}
}

func (m *WrappedCSR) GetRevenueString() string {
	if m != nil {
		return m.RevenueString
	}
	return ""
}

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{1}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{2}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryCSRsRequest is the request type for the Query/CSRs RPC method.
type QueryCSRsRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCSRsRequest) Reset()         { *m = QueryCSRsRequest{} }
func (m *QueryCSRsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCSRsRequest) ProtoMessage()    {}
func (*QueryCSRsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{3}
}
func (m *QueryCSRsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRsRequest.Merge(m, src)
}
func (m *QueryCSRsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRsRequest proto.InternalMessageInfo

func (m *QueryCSRsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCSRsResponse is the response type for the Query/CSRs RPC method.
type QueryCSRsResponse struct {
	Csrs []WrappedCSR `protobuf:"bytes,1,rep,name=csrs,proto3" json:"csrs"`
	// pagination for response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCSRsResponse) Reset()         { *m = QueryCSRsResponse{} }
func (m *QueryCSRsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCSRsResponse) ProtoMessage()    {}
func (*QueryCSRsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{4}
}
func (m *QueryCSRsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRsResponse.Merge(m, src)
}
func (m *QueryCSRsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRsResponse proto.InternalMessageInfo

func (m *QueryCSRsResponse) GetCsrs() []WrappedCSR {
	if m != nil {
		return m.Csrs
	}
	return nil
}

func (m *QueryCSRsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCSRByNFTRequest is the request type for the Query/CSRByNFT RPC method.
type QueryCSRByNFTRequest struct {
	NftId uint64 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId,omitempty"`
}

func (m *QueryCSRByNFTRequest) Reset()         { *m = QueryCSRByNFTRequest{} }
func (m *QueryCSRByNFTRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCSRByNFTRequest) ProtoMessage()    {}
func (*QueryCSRByNFTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{5}
}
func (m *QueryCSRByNFTRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRByNFTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRByNFTRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRByNFTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRByNFTRequest.Merge(m, src)
}
func (m *QueryCSRByNFTRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRByNFTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRByNFTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRByNFTRequest proto.InternalMessageInfo

func (m *QueryCSRByNFTRequest) GetNftId() uint64 {
	if m != nil {
		return m.NftId
	}
	return 0
}

// QueryCSRByNFTResponse is the response type for the Query/CSRByNFT RPC method.
type QueryCSRByNFTResponse struct {
	// csr object queried by nft id
	Csr WrappedCSR `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr"`
}

func (m *QueryCSRByNFTResponse) Reset()         { *m = QueryCSRByNFTResponse{} }
func (m *QueryCSRByNFTResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCSRByNFTResponse) ProtoMessage()    {}
func (*QueryCSRByNFTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{6}
}
func (m *QueryCSRByNFTResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRByNFTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRByNFTResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRByNFTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRByNFTResponse.Merge(m, src)
}
func (m *QueryCSRByNFTResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRByNFTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRByNFTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRByNFTResponse proto.InternalMessageInfo

func (m *QueryCSRByNFTResponse) GetCsr() WrappedCSR {
	if m != nil {
		return m.Csr
	}
	return WrappedCSR{}
}

// QueryCSRByContractRequest is the request type for the Query/CSRByContract RPC method.
type QueryCSRByContractRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryCSRByContractRequest) Reset()         { *m = QueryCSRByContractRequest{} }
func (m *QueryCSRByContractRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCSRByContractRequest) ProtoMessage()    {}
func (*QueryCSRByContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{7}
}
func (m *QueryCSRByContractRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRByContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRByContractRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRByContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRByContractRequest.Merge(m, src)
}
func (m *QueryCSRByContractRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRByContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRByContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRByContractRequest proto.InternalMessageInfo

func (m *QueryCSRByContractRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryCSRByContractResponse is the response type for the Query/CSRByContract RPC method.
type QueryCSRByContractResponse struct {
	// csr object queried by smart contract address
	Csr WrappedCSR `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr"`
}

func (m *QueryCSRByContractResponse) Reset()         { *m = QueryCSRByContractResponse{} }
func (m *QueryCSRByContractResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCSRByContractResponse) ProtoMessage()    {}
func (*QueryCSRByContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{8}
}
func (m *QueryCSRByContractResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCSRByContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCSRByContractResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCSRByContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCSRByContractResponse.Merge(m, src)
}
func (m *QueryCSRByContractResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCSRByContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCSRByContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCSRByContractResponse proto.InternalMessageInfo

func (m *QueryCSRByContractResponse) GetCsr() WrappedCSR {
	if m != nil {
		return m.Csr
	}
	return WrappedCSR{}
}

// QueryTurnstileRequest is the request type for the Query/Turnstile RPC method.
type QueryTurnstileRequest struct {
}

func (m *QueryTurnstileRequest) Reset()         { *m = QueryTurnstileRequest{} }
func (m *QueryTurnstileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTurnstileRequest) ProtoMessage()    {}
func (*QueryTurnstileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{9}
}
func (m *QueryTurnstileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTurnstileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTurnstileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTurnstileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTurnstileRequest.Merge(m, src)
}
func (m *QueryTurnstileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTurnstileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTurnstileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTurnstileRequest proto.InternalMessageInfo

// QueryTurnstileResponse is the response type for the Query/Turnstile RPC method.
type QueryTurnstileResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryTurnstileResponse) Reset()         { *m = QueryTurnstileResponse{} }
func (m *QueryTurnstileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTurnstileResponse) ProtoMessage()    {}
func (*QueryTurnstileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a845ddc1dc245388, []int{10}
}
func (m *QueryTurnstileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTurnstileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTurnstileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTurnstileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTurnstileResponse.Merge(m, src)
}
func (m *QueryTurnstileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTurnstileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTurnstileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTurnstileResponse proto.InternalMessageInfo

func (m *QueryTurnstileResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*WrappedCSR)(nil), "canto.csr.v1.WrappedCSR")
	proto.RegisterType((*QueryParamsRequest)(nil), "canto.csr.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "canto.csr.v1.QueryParamsResponse")
	proto.RegisterType((*QueryCSRsRequest)(nil), "canto.csr.v1.QueryCSRsRequest")
	proto.RegisterType((*QueryCSRsResponse)(nil), "canto.csr.v1.QueryCSRsResponse")
	proto.RegisterType((*QueryCSRByNFTRequest)(nil), "canto.csr.v1.QueryCSRByNFTRequest")
	proto.RegisterType((*QueryCSRByNFTResponse)(nil), "canto.csr.v1.QueryCSRByNFTResponse")
	proto.RegisterType((*QueryCSRByContractRequest)(nil), "canto.csr.v1.QueryCSRByContractRequest")
	proto.RegisterType((*QueryCSRByContractResponse)(nil), "canto.csr.v1.QueryCSRByContractResponse")
	proto.RegisterType((*QueryTurnstileRequest)(nil), "canto.csr.v1.QueryTurnstileRequest")
	proto.RegisterType((*QueryTurnstileResponse)(nil), "canto.csr.v1.QueryTurnstileResponse")
}

func init() { proto.RegisterFile("canto/csr/v1/query.proto", fileDescriptor_a845ddc1dc245388) }

var fileDescriptor_a845ddc1dc245388 = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4d, 0x4f, 0x13, 0x41,
	0x18, 0xc7, 0xbb, 0x50, 0x50, 0x1e, 0xc4, 0xc8, 0xb8, 0x42, 0xbb, 0x92, 0xa5, 0xac, 0x2f, 0x54,
	0x23, 0x3b, 0xb6, 0xc6, 0x2f, 0x40, 0x13, 0x08, 0x17, 0x82, 0x5b, 0x12, 0x13, 0x0e, 0x9a, 0xe9,
	0x76, 0x58, 0x1b, 0x60, 0x67, 0x99, 0x99, 0x16, 0x09, 0xe1, 0xe2, 0xd9, 0x03, 0x89, 0x5f, 0x8a,
	0x23, 0x89, 0x17, 0xbd, 0x18, 0x03, 0x7e, 0x10, 0xb3, 0x33, 0xb3, 0xd0, 0xad, 0x05, 0x12, 0x6f,
	0xdd, 0x79, 0xfe, 0xf3, 0x7f, 0x7e, 0xcf, 0xcb, 0x14, 0x4a, 0x21, 0x89, 0x25, 0xc3, 0xa1, 0xe0,
	0xb8, 0x57, 0xc3, 0xfb, 0x5d, 0xca, 0x0f, 0xfd, 0x84, 0x33, 0xc9, 0xd0, 0x3d, 0x15, 0xf1, 0x43,
	0xc1, 0xfd, 0x5e, 0xcd, 0xb1, 0x23, 0x16, 0x31, 0x15, 0xc0, 0xe9, 0x2f, 0xad, 0x71, 0xe6, 0x22,
	0xc6, 0xa2, 0x5d, 0x8a, 0x49, 0xd2, 0xc1, 0x24, 0x8e, 0x99, 0x24, 0xb2, 0xc3, 0x62, 0x61, 0xa2,
	0x2f, 0x43, 0x26, 0xf6, 0x98, 0xc0, 0x2d, 0x22, 0xa8, 0xb6, 0xc6, 0xbd, 0x5a, 0x8b, 0x4a, 0x52,
	0xc3, 0x09, 0x89, 0x3a, 0xb1, 0x12, 0x1b, 0x6d, 0x39, 0xc7, 0x91, 0x10, 0x4e, 0xf6, 0x32, 0x9b,
	0x99, 0x5c, 0x28, 0xe5, 0x51, 0xe7, 0xde, 0x07, 0x80, 0xf7, 0x9c, 0x24, 0x09, 0x6d, 0x37, 0x9a,
	0x01, 0x7a, 0x01, 0xa3, 0xa1, 0xe0, 0x25, 0xab, 0x62, 0x55, 0x27, 0xeb, 0xd3, 0x7e, 0x3f, 0xbc,
	0xdf, 0x68, 0x06, 0xcb, 0xc5, 0xd3, 0x5f, 0xf3, 0x85, 0x20, 0xd5, 0xa0, 0x67, 0x70, 0x9f, 0xd3,
	0x1e, 0x8d, 0xbb, 0xf4, 0xa3, 0x90, 0xbc, 0x13, 0x47, 0xa5, 0x91, 0x8a, 0x55, 0x9d, 0x08, 0xa6,
	0xcc, 0x69, 0x53, 0x1d, 0x7a, 0x36, 0xa0, 0x77, 0x29, 0xf4, 0x86, 0x82, 0x09, 0xe8, 0x7e, 0x97,
	0x0a, 0xe9, 0xad, 0xc1, 0xc3, 0xdc, 0xa9, 0x48, 0x58, 0x2c, 0x28, 0xaa, 0xc3, 0xb8, 0x86, 0x36,
	0x04, 0x76, 0x9e, 0x40, 0xab, 0x0d, 0x84, 0x51, 0x7a, 0x5b, 0xf0, 0x40, 0x59, 0x35, 0x9a, 0x41,
	0x66, 0x8f, 0x56, 0x00, 0xae, 0x7a, 0x63, 0xbc, 0x9e, 0xfb, 0xba, 0x91, 0x7e, 0xda, 0x48, 0x5f,
	0xcf, 0xc8, 0x34, 0xd2, 0xdf, 0x20, 0x11, 0x35, 0x77, 0x83, 0xbe, 0x9b, 0xde, 0x89, 0x05, 0xd3,
	0x7d, 0xe6, 0x97, 0x94, 0xc5, 0x50, 0xf0, 0x94, 0x71, 0xb4, 0x3a, 0x59, 0x2f, 0xe5, 0x19, 0xaf,
	0x9a, 0x69, 0x38, 0x95, 0x16, 0xad, 0xe6, 0x88, 0x46, 0x14, 0xd1, 0xe2, 0xad, 0x44, 0x3a, 0x61,
	0x0e, 0xe9, 0x15, 0xd8, 0x19, 0xd1, 0xf2, 0xe1, 0xfa, 0xca, 0x66, 0x56, 0xb2, 0x0d, 0x63, 0xf1,
	0xb6, 0x5c, 0x6b, 0xab, 0x6a, 0x8b, 0x81, 0xfe, 0xf0, 0xd6, 0xe0, 0xd1, 0x80, 0xda, 0xd4, 0xf0,
	0xba, 0x7f, 0xd0, 0xb7, 0x95, 0x90, 0x4a, 0xbd, 0xb7, 0x50, 0xbe, 0xb2, 0x6a, 0xb0, 0x58, 0x72,
	0x12, 0xca, 0x2c, 0x7b, 0x09, 0xee, 0x90, 0x76, 0x9b, 0x53, 0xa1, 0x27, 0x37, 0x11, 0x64, 0x9f,
	0xde, 0x3a, 0x38, 0xc3, 0xae, 0xfd, 0x37, 0xc6, 0xac, 0xa9, 0x68, 0xb3, 0xcb, 0x63, 0x21, 0x3b,
	0xbb, 0xd9, 0xdc, 0xbc, 0x3a, 0xcc, 0x0c, 0x06, 0x4c, 0x92, 0x6b, 0xe1, 0xea, 0x3f, 0x8b, 0x30,
	0xa6, 0x2e, 0xa1, 0x1d, 0x18, 0xd7, 0xdb, 0x85, 0x2a, 0x79, 0x8a, 0x7f, 0x97, 0xd7, 0x59, 0xb8,
	0x41, 0xa1, 0x53, 0x7a, 0x73, 0x5f, 0xbe, 0xff, 0xf9, 0x36, 0x32, 0x83, 0x6c, 0xac, 0x9f, 0x9d,
	0x7e, 0x72, 0xe6, 0x45, 0xa2, 0x10, 0x8a, 0xe9, 0x42, 0x21, 0x77, 0x88, 0x51, 0xdf, 0x1a, 0x3b,
	0xf3, 0xd7, 0xc6, 0x4d, 0x1a, 0x47, 0xa5, 0xb1, 0x11, 0xca, 0xa7, 0x51, 0x1b, 0xd7, 0x83, 0xbb,
	0xd9, 0xd4, 0x91, 0x37, 0xdc, 0xa8, 0x7f, 0x81, 0x9c, 0x27, 0x37, 0x6a, 0x4c, 0xc2, 0x05, 0x95,
	0xf0, 0x31, 0x2a, 0xe7, 0x13, 0xc6, 0xdb, 0x12, 0x1f, 0xa9, 0x8d, 0x3b, 0x46, 0x5f, 0x2d, 0x98,
	0xca, 0x0d, 0x1b, 0x2d, 0x5e, 0xe7, 0x3c, 0xb0, 0x45, 0x4e, 0xf5, 0x76, 0xa1, 0xe1, 0xa8, 0x2a,
	0x0e, 0x0f, 0x55, 0x06, 0x0a, 0x37, 0x3a, 0x7c, 0x64, 0x26, 0x7c, 0x8c, 0x0e, 0x60, 0xe2, 0x72,
	0x23, 0xd0, 0xb0, 0x1a, 0x07, 0x17, 0xc9, 0x79, 0x7a, 0xb3, 0xc8, 0x10, 0xcc, 0x2b, 0x82, 0x32,
	0x9a, 0xcd, 0x13, 0xc8, 0x4c, 0xb8, 0xbc, 0x7a, 0x7a, 0xee, 0x5a, 0x67, 0xe7, 0xae, 0xf5, 0xfb,
	0xdc, 0xb5, 0x4e, 0x2e, 0xdc, 0xc2, 0xd9, 0x85, 0x5b, 0xf8, 0x71, 0xe1, 0x16, 0xb6, 0x96, 0xa2,
	0x8e, 0xfc, 0xd4, 0x6d, 0xf9, 0x21, 0xdb, 0xc3, 0x8d, 0xf4, 0xf2, 0xd2, 0x3a, 0x95, 0x07, 0x8c,
	0xef, 0xe8, 0x2f, 0xdc, 0xab, 0xe3, 0xcf, 0xda, 0xec, 0x30, 0xa1, 0xa2, 0x35, 0xae, 0xfe, 0xa8,
	0xdf, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x44, 0xed, 0x0a, 0x6d, 0x65, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// query all registered CSRs
	CSRs(ctx context.Context, in *QueryCSRsRequest, opts ...grpc.CallOption) (*QueryCSRsResponse, error)
	// query a specific CSR by the nftId
	CSRByNFT(ctx context.Context, in *QueryCSRByNFTRequest, opts ...grpc.CallOption) (*QueryCSRByNFTResponse, error)
	// query a CSR by smart contract address
	CSRByContract(ctx context.Context, in *QueryCSRByContractRequest, opts ...grpc.CallOption) (*QueryCSRByContractResponse, error)
	// query the turnstile address
	Turnstile(ctx context.Context, in *QueryTurnstileRequest, opts ...grpc.CallOption) (*QueryTurnstileResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/canto.csr.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CSRs(ctx context.Context, in *QueryCSRsRequest, opts ...grpc.CallOption) (*QueryCSRsResponse, error) {
	out := new(QueryCSRsResponse)
	err := c.cc.Invoke(ctx, "/canto.csr.v1.Query/CSRs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CSRByNFT(ctx context.Context, in *QueryCSRByNFTRequest, opts ...grpc.CallOption) (*QueryCSRByNFTResponse, error) {
	out := new(QueryCSRByNFTResponse)
	err := c.cc.Invoke(ctx, "/canto.csr.v1.Query/CSRByNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CSRByContract(ctx context.Context, in *QueryCSRByContractRequest, opts ...grpc.CallOption) (*QueryCSRByContractResponse, error) {
	out := new(QueryCSRByContractResponse)
	err := c.cc.Invoke(ctx, "/canto.csr.v1.Query/CSRByContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Turnstile(ctx context.Context, in *QueryTurnstileRequest, opts ...grpc.CallOption) (*QueryTurnstileResponse, error) {
	out := new(QueryTurnstileResponse)
	err := c.cc.Invoke(ctx, "/canto.csr.v1.Query/Turnstile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// query all registered CSRs
	CSRs(context.Context, *QueryCSRsRequest) (*QueryCSRsResponse, error)
	// query a specific CSR by the nftId
	CSRByNFT(context.Context, *QueryCSRByNFTRequest) (*QueryCSRByNFTResponse, error)
	// query a CSR by smart contract address
	CSRByContract(context.Context, *QueryCSRByContractRequest) (*QueryCSRByContractResponse, error)
	// query the turnstile address
	Turnstile(context.Context, *QueryTurnstileRequest) (*QueryTurnstileResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CSRs(ctx context.Context, req *QueryCSRsRequest) (*QueryCSRsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CSRs not implemented")
}
func (*UnimplementedQueryServer) CSRByNFT(ctx context.Context, req *QueryCSRByNFTRequest) (*QueryCSRByNFTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CSRByNFT not implemented")
}
func (*UnimplementedQueryServer) CSRByContract(ctx context.Context, req *QueryCSRByContractRequest) (*QueryCSRByContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CSRByContract not implemented")
}
func (*UnimplementedQueryServer) Turnstile(ctx context.Context, req *QueryTurnstileRequest) (*QueryTurnstileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Turnstile not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.csr.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CSRs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCSRsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CSRs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.csr.v1.Query/CSRs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CSRs(ctx, req.(*QueryCSRsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CSRByNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCSRByNFTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CSRByNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.csr.v1.Query/CSRByNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CSRByNFT(ctx, req.(*QueryCSRByNFTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CSRByContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCSRByContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CSRByContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.csr.v1.Query/CSRByContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CSRByContract(ctx, req.(*QueryCSRByContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Turnstile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTurnstileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Turnstile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/canto.csr.v1.Query/Turnstile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Turnstile(ctx, req.(*QueryTurnstileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "canto.csr.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CSRs",
			Handler:    _Query_CSRs_Handler,
		},
		{
			MethodName: "CSRByNFT",
			Handler:    _Query_CSRByNFT_Handler,
		},
		{
			MethodName: "CSRByContract",
			Handler:    _Query_CSRByContract_Handler,
		},
		{
			MethodName: "Turnstile",
			Handler:    _Query_Turnstile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "canto/csr/v1/query.proto",
}

func (m *WrappedCSR) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WrappedCSR) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrappedCSR) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RevenueString) > 0 {
		i -= len(m.RevenueString)
		copy(dAtA[i:], m.RevenueString)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RevenueString)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Csr.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCSRsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCSRsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Csrs) > 0 {
		for iNdEx := len(m.Csrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Csrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCSRByNFTRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRByNFTRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRByNFTRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NftId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NftId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCSRByNFTResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRByNFTResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRByNFTResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Csr.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCSRByContractRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRByContractRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRByContractRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCSRByContractResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCSRByContractResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCSRByContractResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Csr.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTurnstileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTurnstileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTurnstileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTurnstileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTurnstileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTurnstileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WrappedCSR) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Csr.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.RevenueString)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCSRsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCSRsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Csrs) > 0 {
		for _, e := range m.Csrs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCSRByNFTRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NftId != 0 {
		n += 1 + sovQuery(uint64(m.NftId))
	}
	return n
}

func (m *QueryCSRByNFTResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Csr.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCSRByContractRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCSRByContractResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Csr.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTurnstileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTurnstileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WrappedCSR) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WrappedCSR: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WrappedCSR: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Csr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevenueString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevenueString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Csrs = append(m.Csrs, WrappedCSR{})
			if err := m.Csrs[len(m.Csrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRByNFTRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRByNFTRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRByNFTRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			m.NftId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRByNFTResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRByNFTResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRByNFTResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Csr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRByContractRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRByContractRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRByContractRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCSRByContractResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCSRByContractResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCSRByContractResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Csr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTurnstileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTurnstileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTurnstileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTurnstileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTurnstileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTurnstileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
