name: Docker Build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build --tag=canto-network/canto .
      - run: docker run --volume --rm canto-network/canto
